# permissions for end users to edit virtualclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: openvc
    app.kubernetes.io/managed-by: kustomize
  name: virtualcluster-editor-role
rules:
- apiGroups:
  - core.openvc.dev
  resources:
  - virtualclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.openvc.dev
  resources:
  - virtualclusters/status
  verbs:
  - get
