apiVersion: core.openvc.dev/v1alpha1
kind: VirtualCluster
metadata:
  name: sample-vcluster
  namespace: default
spec:
  values:
    exportKubeConfig:
      server: https://sample-vcluster.cluster.openvc.dev:443
      secret:
        name: sample-vcluster-kubeconfig
        namespace: default
    controlPlane:
      distro:
        k3s:
          enabled: true
          # Additional arguments for k3s
          extraArgs:
            - "--disable=traefik"
            - "--disable=metrics-server"
            - "--tls-san=sample-vcluster.cluster.openvc.dev"
      proxy:
        extraSANs:
          - sample-vcluster.cluster.openvc.dev
      statefulSet:
        # Configure high availability
        highAvailability:
          replicas: 1

        # Resource requests/limits
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "2000m"
            memory: "2Gi"
      ingress:
        enabled: true
        host: sample-vcluster.cluster.openvc.dev
        labels: {}
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          nginx.ingress.kubernetes.io/backend-protocol: HTTPS
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
        spec:
          tls:
            - hosts:
                - sample-vcluster.cluster.openvc.dev
              secretName: sample-vcluster-tls
