{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "openvirtualcluster-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openvirtualcluster-operator.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "openvirtualcluster-operator.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector: {}
    ports:
    - port: 8443
      protocol: TCP
    - port: 8081
      protocol: TCP
  egress:
  - {}
{{- end }} 