{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: openvirtualcluster-operator
    app.kubernetes.io/part-of: openvirtualcluster-operator
    {{- include "openvirtualcluster-operator.labels" . | nindent 4 }}
  name: {{ include "openvirtualcluster-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
