apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openvc-default-namespace-role
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - configmaps
  - pods
  - services
  - secrets
  - events
  - endpoints
  - persistentvolumeclaims
  - pods/attach
  - pods/exec
  - pods/log
  - pods/portforward
  - pods/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  - replicasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openvc-default-namespace-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openvc-default-namespace-role
subjects:
- kind: ServiceAccount
  name: openvc-openvirtualcluster-operator
  namespace: openvc-system 