apiVersion: core.openvc.dev/v1alpha1
kind: VirtualCluster
metadata:
  name: k0s-vcluster
  namespace: default
spec:
  values:
    # Configure a different Kubernetes distribution
    # In this example, we're using k0s instead of k3s
    vcluster:
      # Switch from k3s (default) to k0s
      plugin:
        name: k0s
        
      # K0s-specific settings
      k0s:
        version: "v1.27.1-k0s.0"
        # Optional k0s config
        extraConfig: |
          apiVersion: k0s.k0sproject.io/v1beta1
          kind: ClusterConfig
          metadata:
            name: k0s
          spec:
            extensions:
              helm:
                repositories:
                - name: ingress-nginx
                  url: https://kubernetes.github.io/ingress-nginx
                charts:
                - name: ingress-controller
                  chartname: ingress-nginx/ingress-nginx
                  version: "4.6.0"
                  namespace: ingress-nginx
                  
    # Configure a minimal, working setup
    service:
      type: ClusterIP
      
    storage:
      persistence: false 