apiVersion: core.openvc.dev/v1alpha1
kind: VirtualCluster
metadata:
  name: exposed-vcluster
  namespace: default
spec:
  values:
    # Basic vcluster configuration
    vcluster:
      image: rancher/k3s:v1.27.3-k3s1
    
    # Configure the service to expose the virtual cluster
    service:
      # Use NodePort to expose the service on a port on each node
      type: NodePort
      
      # If you have a load balancer available, use LoadBalancer instead
      # type: LoadBalancer
      
      # Configure the node port if using NodePort
      nodePort: 30080
      
      # Configure extra ports to expose
      extraPorts:
        - name: metrics
          port: 8443
          targetPort: 8443
          nodePort: 30081 