apiVersion: core.openvc.dev/v1alpha1
kind: VirtualCluster
metadata:
  name: resource-limited-vcluster
  namespace: default
spec:
  values:
    # Basic vcluster configuration
    vcluster:
      image: rancher/k3s:v1.27.3-k3s1
      
    # Configure resource limits and requests for the virtual cluster
    resources:
      # Resource limits for the vcluster itself
      limits:
        cpu: "1"
        memory: "1Gi"
      
      # Resource requests for the vcluster
      requests:
        cpu: "200m"
        memory: "512Mi"
    
    # Configure resource limits for other components
    syncer:
      resources:
        limits:
          cpu: "500m"
          memory: "256Mi"
        requests:
          cpu: "100m"
          memory: "128Mi"
          
    # Disable telemetry
    telemetry:
      disabled: true 