name: Release Helm Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
  workflow_dispatch:
    inputs:
      chart_version:
        description: 'Chart version to release (leave empty to use values in Chart.yaml)'
        required: false
        type: string
      app_version:
        description: 'App version to release (leave empty to use values in Chart.yaml)'
        required: false
        type: string

jobs:
  release-charts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.3

      - name: Update chart version if provided
        if: ${{ github.event.inputs.chart_version != '' }}
        run: |
          CHART_VERSION="${{ github.event.inputs.chart_version }}"
          APP_VERSION="${{ github.event.inputs.app_version }}"
          
          if [ -n "$CHART_VERSION" ]; then
            echo "Updating chart version to $CHART_VERSION"
            sed -i "s/^version:.*/version: $CHART_VERSION/" charts/openvirtualcluster-operator/Chart.yaml
          fi
          
          if [ -n "$APP_VERSION" ]; then
            echo "Updating app version to $APP_VERSION"
            sed -i "s/^appVersion:.*/appVersion: \"$APP_VERSION\"/" charts/openvirtualcluster-operator/Chart.yaml
          fi

      - name: Update dependencies
        run: |
          for chart in charts/*; do
            if [ -d "$chart" ]; then
              echo "Updating dependencies for $chart"
              helm dependency update "$chart"
            fi
          done

      - name: Package Helm Charts
        run: |
          mkdir -p .cr-release-packages
          for chart in charts/*; do
            if [ -d "$chart" ]; then
              echo "Packaging $chart"
              helm package "$chart" -d .cr-release-packages
            fi
          done

      - name: Create index file
        run: |
          helm repo index .cr-release-packages --url https://openvirtualcluster.github.io/openvirtualcluster-operator/
          cp .cr-release-packages/index.yaml .
          # Copy the HTML index page to the release directory
          cp charts/index.html .cr-release-packages/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .cr-release-packages
          keep_files: true

      - name: Update README with Helm Chart Info
        run: |
          # Create or update index section in the main README
          if [ -f "README.md" ]; then
            # Extract chart info
            CHART_NAME=$(grep -m 1 "name:" charts/openvirtualcluster-operator/Chart.yaml | awk '{print $2}')
            CHART_VERSION=$(grep -m 1 "version:" charts/openvirtualcluster-operator/Chart.yaml | awk '{print $2}')
            APP_VERSION=$(grep -m 1 "appVersion:" charts/openvirtualcluster-operator/Chart.yaml | awk '{print $2}' | tr -d '"')
            
            # Check if Helm Chart Installation section exists
            if grep -q "## Helm Chart Installation" README.md; then
              # Update existing section
              sed -i '/## Helm Chart Installation/,/```/c\## Helm Chart Installation\n\nThe OpenVirtualCluster Operator can be installed via Helm chart:\n\n```bash\n# Add the OpenVirtualCluster Helm repository\nhelm repo add openvirtualcluster https://openvirtualcluster.github.io/openvirtualcluster-operator/\n\n# Update your Helm repositories\nhelm repo update\n\n# Install the chart\nhelm install openvirtualcluster openvirtualcluster/openvirtualcluster-operator --version '"$CHART_VERSION"'\n```\n\nCurrent chart version: '"$CHART_VERSION"' (App version: '"$APP_VERSION"')' README.md
            else
              # Add new section before the License section or at the end
              if grep -q "## License" README.md; then
                sed -i '/## License/i\## Helm Chart Installation\n\nThe OpenVirtualCluster Operator can be installed via Helm chart:\n\n```bash\n# Add the OpenVirtualCluster Helm repository\nhelm repo add openvirtualcluster https://openvirtualcluster.github.io/openvirtualcluster-operator/\n\n# Update your Helm repositories\nhelm repo update\n\n# Install the chart\nhelm install openvirtualcluster openvirtualcluster/openvirtualcluster-operator --version '"$CHART_VERSION"'\n```\n\nCurrent chart version: '"$CHART_VERSION"' (App version: '"$APP_VERSION"')\n\n' README.md
              else
                echo -e "\n## Helm Chart Installation\n\nThe OpenVirtualCluster Operator can be installed via Helm chart:\n\n\`\`\`bash\n# Add the OpenVirtualCluster Helm repository\nhelm repo add openvirtualcluster https://openvirtualcluster.github.io/openvirtualcluster-operator/\n\n# Update your Helm repositories\nhelm repo update\n\n# Install the chart\nhelm install openvirtualcluster openvirtualcluster/openvirtualcluster-operator --version $CHART_VERSION\n\`\`\`\n\nCurrent chart version: $CHART_VERSION (App version: $APP_VERSION)\n" >> README.md
              fi
            fi
            
            # Commit the changes
            git add README.md
            git commit -m "Update Helm chart installation instructions to version $CHART_VERSION" || true
            git push origin main || true
          fi 